---
- hosts: all
  gather_facts: False
  tasks:
  - name: deploying yum packages
    yum: name={{item}} state=present
    with_items: [libselinux-python,gcc,gcc-c++,sysstat,strace,automake,autoconf,epel-release,git,wget,libselinux-python,openssl-devel]
  - name: deploying epel yum packages
    yum: name={{item}} state=present
    with_items: []
  - name: Installing openvz repo
    command: creates=/etc/yum.repos.d/openvz.repo chdir=/etc/yum.repos.d wget https://download.openvz.org/openvz.repo
    register: ovz
  - name: Removing kernel-headers
    yum: name={{item}} state=absent
    with_items: [kernel-headers,kernel-devel]
    when: ovz.changed
  - name: Installing OpenVZ
    yum: name={{item}} state=present
    with_items: [vzkernel,vzctl,vzkernel-headers,vzkernel-devel]
  - name: Enabling Connection Tracking on Hardware Node
    register: ct
    lineinfile: path=/etc/modprobe.d/openvz.conf state=present regexp='^options nf_conntrack ip_conntrack_disable_ve0=' line='options nf_conntrack ip_conntrack_disable_ve0=0'
  - name: Rebooting Node
    command: reboot
    when: ovz.changed or ct.changed
  - name: Pausing for reboot
    pause: minutes=5
    when: ovz.changed
  - name: Removing kernel
    yum: name={{item}} state=absent
    with_items: [kernel]
    ignore_errors: True
  - name: Linking vz-scripts to /z/
    file: state=link src=/etc/sysconfig/vz-scripts dest=/z
  - name: Copying e vzctl enter script
    copy: src=ansibleFiles/e dest=/usr/sbin/e mode=0700
